heptastique/onlygo

src/main/java/smart/Controller/UserController.java, src/main/java/smart/Services/UserService.java
=> new service

.travis.yml, README.md, codecov.yml, pom.xml
La couverture des tests est maintenant suivie automatiquement par Codecov
Un badge indiquant la couverture des tests sur master a été ajoutée
=> Create coverage config

.gitignore, .travis.yml, src/main/java/smart/DTO/PollutionDataDto.java, src/main/java/smart/Entities/DonneeAthmospherique.java, src/main/java/smart/Repositories/DonneeAthmospheriqueRepository.java, src/main/java/smart/Services/DonneeAthmospheriqueService.java, src/main/resources/application.properties.example, src/test/java/test/Services/DonneeAthmospheriqueServiceTest.java
=> Pollution data

src/main/java/smart/Entities/Cercle.java, src/main/java/smart/Entities/Point.java, src/main/java/smart/Entities/Zone.java
=> zone added to model but no zone in the db (yet)

pom.xml
Ne me demandez pas pourquoi ça marche, mais ça marche
https://stackoverflow.com/questions/43191294/hibernate-error-executing-ddl-via-jdbc-statement#43295074
=> Add hibernate property

src/main/java/smart/DTO/PollutionDataDto.java, src/main/java/smart/DTO/PollutionDataElemDto.java, src/main/java/smart/DTO/PollutionDataIndicesDto.java, src/main/java/smart/Entities/DonneeAthmospherique.java, src/main/java/smart/Services/DonneeAthmospheriqueService.java, src/test/java/test/Services/DonneeAthmospheriqueServiceTest.java
=> Persist atmo data

src/main/java/smart/Services/UserService.java, src/test/java/test/Services/UserServiceTest.java
=> User service add user test

src/main/java/smart/Services/AuthorityService.java, src/main/java/smart/Services/UserService.java, src/test/java/test/Services/AuthorityServiceTest.java, src/test/java/test/Services/UserServiceTest.java
=> Use authority service

src/test/java/test/Services/UserServiceTest.java
=> more tests

src/test/java/test/Services/UserServiceTest.java
=> Fix malformed test

src/main/java/smart/Algorithms/FindByJour.java, src/main/java/smart/Entities/TimeFrame.java, src/main/java/smart/Services/TimeFrameService.java
=> see branch name

src/main/java/smart/Entities/Activity.java, src/main/java/smart/Entities/Realisation.java
=> Add centre interet to activity and realisation

src/main/java/smart/Algorithms/FindByJour.java
this enables different calendars instead of relying on the hypothesis that monday is the first day of
the week(true in some environments)
=> set calendar first day of the week to monday

src/main/java/smart/Entities/TimeFrame.java, src/main/java/smart/Entities/WeatherData.java, src/main/java/smart/Services/DonneeAthmospheriqueService.java, src/main/java/smart/Services/TimeFrameService.java, src/main/java/smart/Services/WeatherDataService.java
=> Fix update time

src/main/java/smart/Algorithms/ProgramActivities.java, src/main/java/smart/Controller/ActivityController.java, src/main/java/smart/DTO/ActivityDTO.java, src/main/java/smart/Entities/Activity.java, src/main/java/smart/Entities/TimeFrame.java, src/main/java/smart/Services/ActivityService.java, src/main/java/smart/Services/ProgrammeService.java, src/test/java/test/Controllers/ActivityControllerTest.java, src/test/java/test/Services/ActivityServiceTest.java
Closes #44 
Closes #84 
First Version of Program Generation Algorithm
=> Program Generation Algorithm

codecov.yml
Pour être sûr que ce qui est fait et sera fait ne sera plus à refaire
=> Enforce patch coverage 

src/main/java/smart/Algorithms/ProgramActivities.java
=> Program Generation Algorithm uses SportService::getSport(String name) 

src/main/java/smart/Algorithms/ProgramActivities.java
=> Fix TimeFrameCentreInteret Index Out of Bounds

src/main/java/smart/Algorithms/ProgramActivities.java, src/main/java/smart/Controller/UserController.java, src/main/java/smart/Entities/Programme.java, src/main/java/smart/Services/UserService.java, src/test/java/test/Controllers/UserControllerTest.java
=> Objectif distance par programme et par utilisateur

src/main/java/smart/Algorithms/ProgramActivities.java
=> Fix Program Activity TimeFrame in current Week

docs/Utilisateurs.md, src/main/java/smart/DTO/UserDto.java, src/main/java/smart/Services/UserService.java, src/test/java/test/Controllers/UserControllerTest.java, src/test/java/test/Services/RealisationServiceTest.java, src/test/java/test/Services/UserServiceTest.java
Nouvelle inscription utilisateur, avec localisation dès l'inscription, ainsi que distance max par séance, avec la doc qui va avec.
Il reste deux tests qui ne passent pas, ce serait bien que @lulucasono les corrige, puisque c'est lui qui les a écrit
=> New inscription endpoint

src/main/java/smart/DTO/UserDto.java, src/main/java/smart/Services/UserService.java, src/test/java/test/Controllers/UserControllerTest.java, src/test/java/test/Services/RealisationServiceTest.java, src/test/java/test/Services/UserServiceTest.java
Because j'aime bien mix des variables names
Ces modifications sont nécessaires pour être en phase avec les attributs du DTO et pour que le front (dernière version sur master) puisse fonctionner
=> Rename Localisation to Location

src/main/java/smart/Algorithms/ProgramActivities.java, src/main/java/smart/Controller/ProgrammeController.java
=> Activities Generation Program handles CentreInteret and Day Variation

src/main/java/smart/Algorithms/ProgramActivities.java
=> Activities Generation Program splits Week Objective into 3 Activities

src/main/java/smart/Entities/Activity.java, src/main/java/smart/Entities/Programme.java
=> Taux completion

src/main/java/smart/Algorithms/ProgramActivities.java
=> Program Generation Algorithm Refactoring

src/main/java/smart/Algorithms/ProgramActivities.java
=> Get Sport ID instead of using Switch

src/main/java/smart/Algorithms/ProgramActivities.java, src/main/java/smart/Entities/Programme.java, src/main/java/smart/Entities/User.java, src/main/java/smart/Services/UserService.java
Si @Raul6469 pouvait tester, et me dire si c'est bon, ce serait cool. Merci.
=> Fix generate on register

src/main/java/smart/Services/UserService.java
=> Set nbSessions when adding new user
